### ISSUE TITLE
Excessive drops from Enchanted Silent Gear weapons

### ISSUE THREAD

**Issue by Saporous** [stal111/Forbidden-Arcanus#64] opened 2020-05-26 17:44 UTC
## Versions
- **Forbidden Arcanus**: forbidden_arcanus-1.15.2-1.3.1.jar
- **Modpack**: Valhelsia 2 2.21a
- **Optifine Installed**: No 
- **Forge**: 31.2.0

### Related Mod Version
- **Silent Gear**: 1.15.2-1.7.0+93
- **Silent's Gems**: N/A
- **Silent Lib**: SilentLib-1.15.2-4.6.1+49.jar

## Expected Behavior
I was expecting a 1-3 extra vanilla and modded items to drop when I enchanted the machete with Fortune 3.

## Actual Behavior
Killing an Enderman dropped 4 stacks of the Ender Pearl Fragments from Forbidden&Arcanus. Killing a bat dropped 10+ stacks of Bat Wings also from Forbidden&Arcanus.

## Links/Images
https://i.imgur.com/YWmgJdD.png.

## Steps to Reproduce the Problem
1. Enchant weapon with Fortune 3 and use a Bone for the tool rod (to grant Luck)
2. Kill an Enderman or Bat to drop stacks upon stacks of Forbidden&Arcanus items

**Comment by Saporous** [comment] 2020-05-26 17:46
Here is the associated Silent Gear issue: https://github.com/SilentChaos512/Silent-Gear/issues/129

**Comment by Vaelzan** [comment] 2020-05-27 17:11
Note: This isn't just Silent Gear. The same excessive loot can be found in Dungeon Chests.

**Comment by Vaelzan** [comment] 2020-05-27 17:15
Pure speculation: I wonder if there could be any situation where "onLootTableLoad(LootTableLoadEvent event)" is called more than once? If that were called quite a few times it would result in the same behaviour, but I don't know why that would happen. It's something that's easy enough to safety check (just set a flag so that it can only run once no matter how many times it is called) but it may not be what is causing it.

**Comment by Vaelzan** [comment] 2020-05-29 06:05
I should probably update this... It actually does seem like Silent Gear could be involved (but not necessarily at fault), as they recently added a Lucky trait. The issue here appears to be related to the vanilla luck attribute being increased substantially and that any mod that utilises bonus rolls is impacted. This notably impacts Forbidden & Arcanus due to all the loot being bonus loot injected into enemies or chest loot tables, but it is also seen in MineColonies. I don't believe the issue is caused by Forbidden and Arcanus in the slightest, it just gets impacted substantially due to the nature of the loot being handled via bonus rolls.

I'll try to test further when I have spare time.

**Comment by Vaelzan** [comment] 2020-05-31 13:35
Fixed in Silent Gear now. This can be closed. :)

**Comment by stal111** [comment] 2020-05-31 21:34
Thanks for investigating! :)

**Closed as completed by stal111** 2020-05-31 21:34 UTC
