### ISSUE TITLE
Crashing while loading Minecraft

### ISSUE THREAD

**Issue by cfnnit** [stal111/Forbidden-Arcanus#345] opened 2023-05-17 20:29 UTC
**Describe the bug**
Crashing while loading Minecraft

**To Reproduce**
When I try to start the game, Minecraft fails to turn on and leaves a log like the one below.
```
[18May2023 05:24:12.794] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, Gotoh_Hitori, --version, forge-45.0.64, --gameDir, C:\Users\--\curseforge\minecraft\Instances\44, --assetsDir, C:\Users\ag214\curseforge\minecraft\Install\assets, --assetIndex, 3, --uuid, 88e7da44a52241fb80275a66466f4da9, --accessToken, ????????, --clientId, OWRlMWU2YzEtZjA4Ny00YWMzLThjZWUtNzhjZTVlM2ZjYTlj, --xuid, 2535467144262883, --userType, msa, --versionType, release, --width, 1024, --height, 768, --launchTarget, forgeclient, --fml.forgeVersion, 45.0.64, --fml.mcVersion, 1.19.4, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20230314.122934]
[18May2023 05:24:12.802] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher 10.0.8+10.0.8+main.0ef7e830 starting: java version 17.0.3 by Microsoft; OS Windows 10 arch amd64 version 10.0
[18May2023 05:24:15.131] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/C:/Users/ag214/curseforge/minecraft/Install/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2397!/ Service=ModLauncher Env=CLIENT
[18May2023 05:24:16.226] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file C:\Users\ag214\curseforge\minecraft\Install\libraries\net\minecraftforge\fmlcore\1.19.4-45.0.64\fmlcore-1.19.4-45.0.64.jar is missing mods.toml file
[18May2023 05:24:16.230] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file C:\Users\ag214\curseforge\minecraft\Install\libraries\net\minecraftforge\javafmllanguage\1.19.4-45.0.64\javafmllanguage-1.19.4-45.0.64.jar is missing mods.toml file
[18May2023 05:24:16.234] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file C:\Users\ag214\curseforge\minecraft\Install\libraries\net\minecraftforge\lowcodelanguage\1.19.4-45.0.64\lowcodelanguage-1.19.4-45.0.64.jar is missing mods.toml file
[18May2023 05:24:16.237] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file C:\Users\ag214\curseforge\minecraft\Install\libraries\net\minecraftforge\mclanguage\1.19.4-45.0.64\mclanguage-1.19.4-45.0.64.jar is missing mods.toml file
[18May2023 05:24:16.443] [main/WARN] [net.minecraftforge.jarjar.selection.JarSelector/]: Attempted to select a dependency jar for JarJar which was passed in as source: curios. Using Mod File: C:\Users\ag214\curseforge\minecraft\Instances\44\mods\curios-forge-1.19.4-5.1.5.3.jar
[18May2023 05:24:16.443] [main/INFO] [net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator/]: Found 8 dependencies adding them to mods collection
[18May2023 05:24:22.759] [main/INFO] [mixin/]: Compatibility level set to JAVA_17
[18May2023 05:24:22.847] [main/ERROR] [mixin/]: Mixin config vinery-common.mixins.json does not specify "minVersion" property
[18May2023 05:24:22.849] [main/ERROR] [mixin/]: Mixin config vinery.mixins.json does not specify "minVersion" property
[18May2023 05:24:23.016] [main/ERROR] [mixin/]: Mixin config radon.mixins.json does not specify "minVersion" property
[18May2023 05:24:23.117] [main/INFO] [cpw.mods.modlauncher.LaunchServiceHandler/MODLAUNCHER]: Launching target 'forgeclient' with arguments [--version, forge-45.0.64, --gameDir, C:\Users\--\curseforge\minecraft\Instances\44, --assetsDir, C:\Users\ag214\curseforge\minecraft\Install\assets, --uuid, 88e7da44a52241fb80275a66466f4da9, --username, Gotoh_Hitori, --assetIndex, 3, --accessToken, ????????, --clientId, OWRlMWU2YzEtZjA4Ny00YWMzLThjZWUtNzhjZTVlM2ZjYTlj, --xuid, 2535467144262883, --userType, msa, --versionType, release, --width, 1024, --height, 768]
[18May2023 05:24:23.371] [main/INFO] [fpsreducer/]: OptiFine was NOT detected.
[18May2023 05:24:23.375] [main/INFO] [fpsreducer/]: OptiFabric was NOT detected.
[18May2023 05:24:23.448] [main/WARN] [mixin/]: Reference map 'template.refmap.json' for dusk.mixins.json could not be read. If this is a development environment you can ignore this message
[18May2023 05:24:23.451] [main/WARN] [mixin/]: Reference map 'trashslot.refmap.json' for trashslot.mixins.json could not be read. If this is a development environment you can ignore this message
[18May2023 05:24:23.476] [main/WARN] [mixin/]: Reference map 'configured.refmap.json' for configured.mixins.json could not be read. If this is a development environment you can ignore this message
[18May2023 05:24:23.774] [main/INFO] [Canary/]: Loaded configuration file for Canary: 111 options available, 0 override(s) found
[18May2023 05:24:23.849] [main/WARN] [mixin/]: Reference map 'apexcore.refmap.json' for apexcore.mixins.json could not be read. If this is a development environment you can ignore this message
[18May2023 05:24:25.958] [main/INFO] [fpsreducer/]: bre2el.fpsreducer.mixin.RenderSystemMixin will be applied.
[18May2023 05:24:25.960] [main/INFO] [fpsreducer/]: bre2el.fpsreducer.mixin.WindowMixin will NOT be applied because OptiFine was NOT detected.
[18May2023 05:24:26.205] [main/WARN] [mixin/]: Error loading class: vectorwing/farmersdelight/common/block/TomatoVineBlock (java.lang.ClassNotFoundException: vectorwing.farmersdelight.common.block.TomatoVineBlock)
[18May2023 05:24:26.205] [main/WARN] [mixin/]: @Mixin target vectorwing.farmersdelight.common.block.TomatoVineBlock was not found supplementaries.mixins.json:CompatFarmersDelightMixin
[18May2023 05:24:27.707] [main/INFO] [memoryleakfix/]: [MemoryLeakFix] Will be applying 3 memory leak fixes!
[18May2023 05:24:27.707] [main/INFO] [memoryleakfix/]: [MemoryLeakFix] Currently enabled memory leak fixes: [targetEntityLeak, biomeTemperatureLeak, hugeScreenshotLeak]
[18May2023 05:24:31.016] [pool-3-thread-1/WARN] [mixin/]: @Final field f_20945_:Ljava/util/Map; in vinery-common.mixins.json:LivingEntityMixin should be final
[18May2023 05:24:31.874] [pool-3-thread-1/WARN] [com.stevekung.fishofthieves.FishOfThieves/]: This is the stupidest thing I've ever made in Minecraft modding history...
[18May2023 05:24:35.844] [Datafixer Bootstrap/INFO] [com.mojang.datafixers.DataFixerBuilder/]: 183 Datafixer optimizations took 286 milliseconds
[18May2023 05:24:39.486] [Client Shutdown Thread/ERROR] [net.minecraft.client.main.Main/]: Caught previously unhandled exception :
org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:156) ~[modlauncher-10.0.8.jar:10.0.8+10.0.8+main.0ef7e830]
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-10.0.8.jar:?]
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-10.0.8.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-10.0.8.jar:?]
	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113) ~[securejarhandler-2.1.6.jar:?]
	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.6.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.6.jar:?]
	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.6.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.6.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.client.main.Main$2.run(Main.java:151) ~[client-1.19.4-20230314.122934-srg.jar%23378!/:?]
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector forbiddenArcanus_renderTooltipInternal(Lnet/minecraft/client/gui/screens/inventory/tooltip/TooltipRenderUtil$BlitPainter;Lorg/joml/Matrix4f;Lcom/mojang/blaze3d/vertex/BufferBuilder;IIIII)V in forbidden_arcanus.mixins.json:ScreenMixin failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap forbidden_arcanus.refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1362) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1051) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:383) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:365) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	... 14 more
```

**Expected behavior**
 I thought it might be an issue with an optimization mode like rubidium,
So I tried disabling that mode and restarting, but that didn't work.

**Screenshots**
-

**Versions**
 - Forbidden & Arcanus: 1.19.4-2.2.0-beta1
 - Valhelsia Core: 1.19.4-0.5.0
 - Forge: 45.0.64

**Additional context**
-

**Comment by OBS3SS1ON** [comment] 2023-05-18 02:55
same problem, i think the error comes from valhelsia_core-forge-1.19.4-0.5.0
Forge: 45.0.59

**Comment by stal111** [comment] 2023-06-06 11:13
This was caused by a forge change. Update to 1.19.4-2.2.0-beta2 and this should be fixed.

**Closed as completed by stal111** 2023-06-06 11:13 UTC
Labels: Type: Bug
