### ISSUE TITLE
[1.16.5] inventory mixin crash

### ISSUE THREAD

**Issue by jeremiahwinsley** [stal111/Forbidden-Arcanus#245] opened 2022-03-15 16:16 UTC
**Describe the bug**
ItemStack.getTag is marked as nullable, but returning null will crash the game due to this check: https://github.com/stal111/Forbidden-Arcanus/blob/a915c22ab3bed69f3c27ae0d2f278158d102a6c5/src/main/java/com/stal111/forbidden_arcanus/mixin/ItemMixin.java#L32

This method is marked as `@Nullable`, so returning null is valid here.

I don't know which specific item returned null here, but here's a crash report from this.
https://gist.github.com/jeremiahwinsley/8f192399b1ec777c902dac69c2c0ef7c

**Expected behavior**
This should not crash when returning null.

**Versions**
 - Forbidden & Arcanus: forbidden_arcanus-16.2.3.jar
 - Valhelsia Core: valhelsia_core-16.0.13a.jar
 - Forge: 36.2.28

**Comment by stal111** [comment] 2022-03-15 20:51
Not sure how that can happen. If you take a look at the condition above you can see that I check if the damage value of the item is 0. And if you look into IForgeItem where this method is implemented you can see that it always returns 0 if the item has no tag.

![getDamage](https://user-images.githubusercontent.com/48628578/158469824-f5d54840-a851-46d2-9afc-d9e30663df84.png)

So in theory the call to stack.getItem() should not be possible if the item has no tag.

Only thing I can think of is that some other mod modifies that method in some way, meaning it's most likely a mod conflict as I never heard of such a crash with this part of the code being present for multiple months now.

**Comment by stal111** [comment] 2022-04-24 18:49
Closing this as I can't reproduce it and 1.16.5 is no longer supported.

**Closed as completed by stal111** 2022-04-24 18:49 UTC
Labels: Type: Bug
