### ISSUE TITLE
Broken Vanilla Textures

### ISSUE THREAD

**Issue by ClaudiusMinimus** [stal111/Forbidden-Arcanus#70] opened 2020-06-22 03:12 UTC
I have a tester for my pack in development that gave me a screenshot of broken textures without any 3rd party texture pack. He is not running Optifine.

Core I5 4690k, 16 gigs Ram (10gigs to java) GTX 1660 TI Current Nvida drivers (as of today)
- Minecraft Version: 1.15.2
- Operating System: Windows 10 Pro 1909
- Java Version: 1.8.0_251, Oracle Corporation
- Forge: 31.2.20
- Forbidden Arcanus 1.15.2-1.3.1

![2020-06-21_23 22 27](https://user-images.githubusercontent.com/17887664/85245004-82c3e800-b403-11ea-8bf9-400aafe01243.png)

**Comment by stal111** [comment] 2020-06-24 20:03
That sometimes happens randomly, should be fixed with simply restating the game. I will need to do some more investigation to find the cause for this issue.

**Comment by stal111** [comment] 2021-02-14 11:12
Finally fixed in 16.2.0-beta-1.

**Closed as completed by stal111** 2021-02-14 11:12 UTC
