### ISSUE TITLE
Minecraft not loading

### ISSUE THREAD

**Issue by ALEILGOD** [stal111/Forbidden-Arcanus#404] opened 2024-03-18 14:54 UTC
When i load Minecraft it says error during mod loading

I'm on:
Minecraft 1.20.1
Forge 47.2.0

I have other mods that never had conflicts with Forbidden & arcanus but now there is an error.

The versions i used are:
Valhelsia Core: 1.1.2
Forbidden & Arcanus: 2.2.5

In Prism Launcher the version is not shown neither for Valhelsia Core and neither for forbidden & arcanus.
Here are the sreenshots
![immagine_2024-03-18_155210028](https://github.com/stal111/Forbidden-Arcanus/assets/116183327/7263cc25-77e6-45b4-966a-fba84f00aca3)

![immagine_2024-03-18_155230460](https://github.com/stal111/Forbidden-Arcanus/assets/116183327/a0dc534a-154b-4690-a2bf-59492b6badbd)

![immagine_2024-03-18_155416211](https://github.com/stal111/Forbidden-Arcanus/assets/116183327/1eca8687-0c6c-4ee6-bc92-0233b2293b19)

**Comment by MrCatlio** [comment] 2024-03-19 11:39
try downgrading the Valhelsia Core mod since the latest version of the mod cause forbidden & arcanus to crash on start-up!

**Comment by stal111** [comment] 2024-03-19 15:08
Duplicate of #403

**Closed as completed by stal111** 2024-03-19 15:08 UTC
Labels: Type: Bug
