### ISSUE TITLE
Crash in Forge 1.18.2

### ISSUE THREAD

**Issue by Archilyte** [stal111/Forbidden-Arcanus#305] opened 2022-10-03 00:40 UTC
**Describe the bug**
Game doesn't even start, just generates a crash report

**To Reproduce**
1. Install "Forbidden and Arcanus" and dependencies
2. Run Minecraft
3. See error

**Expected behavior**
The game would have been runnign normally

**Logs**
https://gist.github.com/Archilyte/4f98b61a9e8d299c1aed97ca2758305a (both latest and crash log is included)

**Versions**
 - Forbidden & Arcanus: forbidden_arcanus-1.18.2-2.1.0-beta3.jar
 - Valhelsia Core: valhelsia_core-forge-1.18.2-0.4.0.jar
 - Forge: 40.1.73

**Additional context**
I tried with and without Optifine, in case if you're thinking Optifine is the issue

**Comment by Sakatsuky** [comment] 2022-10-03 12:49
For me it's crashing only when using optfine, i tried with forge .54 .68 .74 and .80 and none crashed.
Edit: tried with valhelsia core 0.3.1 and it's working with optfine forbidden arcanus beta3, but when using valhelsia core 0.4.0 with optfine it crashes

**Comment by Archilyte** [comment] 2022-10-03 21:55
@Sakatsuky Thank you! Downgrading Valhelsia Core seems to have solved the issue for now!

**Comment by stal111** [comment] 2022-10-04 16:24
That crash you included is directly related to optifine. If you also get a crash with Optifine removed, please upload a second crash log as otherwise I won't be able to find the cause.

**Comment by Archilyte** [comment] 2022-10-04 22:29
huh. I guess it is caused by Optifine...

**Comment by stal111** [comment] 2022-10-20 17:42
We currently can't fix this due to Optifine being closed source and as it's Valhelsia Core that is incompatible I'm going to close this issue.

**Closed as completed by stal111** 2022-10-20 17:42 UTC
Labels: Type: Bug
