### ISSUE TITLE
Bigger Reactors and Forbidden Arcanus Crash

### ISSUE THREAD

**Issue by Tomatoh** [stal111/Forbidden-Arcanus#233] opened 2022-01-17 18:26 UTC
Tracked down a crash at world creation in single player and multiplayer stating that 

com.google.gson.JsonParseException: Error loading registry data: Unknown tag: forbidden_arcanus:darkstone_ore_replaceables

The crash is between forbidden_arcanus-1.18.1-2.0.1.jar and biggerreactors-1.18.1-0.6.0-beta.jar

ruled out valhelsia_core-1.18.1-0.3.1.jar (forbidden arcus), quartz-1.18.1-0.0.0-beta.jar (bigger reactors), and phosphophyllite-1.18.1-0.6.0-beta.jar (bigger reactors)

Definitely reproducable by just loading those 5 files

**Comment by Tomatoh** [comment] 2022-01-17 18:29
reported to Bigger Reactors as well https://github.com/BiggerSeries/BiggerReactors/issues/38

and in lieu can use extreme reactors(ExtremeReactors2-1.18.1-2.0.38.jar) which uses zerocore2(ZeroCore2-1.18.1-2.1.11.jar}

**Comment by stal111** [comment] 2022-01-19 17:07
Could you please test if it still crashes with f&a 1.18.1-2.0.2?

**Comment by Gbergz** [comment] 2022-01-19 17:14
@stal111 Just tried it myself, crashes still.
Edit: Crashreport https://gist.github.com/Gbergz/41981d60b8e868570ab67ba33a664739

**Comment by lukiono** [comment] 2022-01-23 13:15
can confirm this bug.
same error as in the log Gbergz sended. same screen, latest mod versions and infinite reproducible;
https://mclo.gs/86yJj0V

**Comment by RogueLogix** [comment] 2022-01-24 21:13
I'm inclined to say that this issue isn't on my side, given that I don't see any of my code or mixins in the stack, along with not touching anything seemingly related.

**Comment by echilda** [comment] 2022-01-30 15:57
Also seeing this issue

**Comment by stal111** [comment] 2022-01-31 21:13
Should be fixed in 1.18.1 - 2.0.3. Didn't found the cause but I fixed it for now by simply removing the use of the mentioned tag.

**Closed as completed by stal111** 2022-01-31 21:13 UTC
