### ISSUE TITLE
Crash when Finishing the tier 2 Forge upgrade recipe

### ISSUE THREAD

**Issue by DarianStardust** [stal111/Forbidden-Arcanus#365] opened 2023-09-20 15:00 UTC
Edit: It seems the crash was caused by Rubidium most recent versions, I downgraded to 0.6.5 rubidium and now the crashing stopped, even for another mod where I was having similar crash issue.
  I guess this can be closed, but have a warning regarding rubidium maybe?

**Describe the bug**
when placing the materials for the first upgrade of Hephestus forge on the pedestals/forge UI, placing the Final material that completes the recipe, regardless of order (placing final ingredient on pedestal or forge leads to the same outcome) the game crashes

**To Reproduce**
1. on the pedestals, place the x4 spawner shards, 4x Arcane crystals, and 1x Edel Log in hephestus forge, Order of placement doesn't matter, Edel log>4xArcane crystals>3 spawner shards +1 final shard will crash as well- the last material that completes the recipe (Not the Circle, The recipe, 8 filled pedestals dont cause a crash by itself, will crash the game.

**Expected behavior**
The forge to upgrade to tier 2, or stay still until I use the mod's hammer(?) Idk what's supposed to happen exactly

**Versions**
 - Forbidden & Arcanus: 1.20.1 (2.2.0)
 - Valhelsia Core: 1.20.1 (1.1.1)
 - Forge: 47.1.43

Crash Log-chan uwu
[latest.log](https://github.com/stal111/Forbidden-Arcanus/files/12674514/latest.log)

**Comment by stal111** [comment] 2023-09-27 19:39
Yeah going to close this as it's caused by Rubidium. If it also affects other mods it's very likely that this crash isn't caused on our side and instead needs to be fixed by Rubidium. It would be awesome if you could open an issue on their bug tracker so they can take care of it.

**Closed as completed by stal111** 2023-09-27 19:39 UTC
Labels: Type: Bug
