### ISSUE TITLE
Crash on Client Start 1.15.1 -1.2- Beta - 4

### ISSUE THREAD

**Issue by GnomeBeard** [stal111/Forbidden-Arcanus#56] opened 2020-04-12 03:21 UTC
The game crashed whilst initializing game
Error: java.lang.NullPointerException: Registry Object not present: forbidden_arcanus:soul

[crash-2020-04-11_22.16.15-client.txt](https://github.com/stal111/Forbidden-Arcanus/files/4465796/crash-2020-04-11_22.16.15-client.txt)

**Comment by stal111** [comment] 2020-04-17 20:06
Could you please try if this also happens with only forbidden & arcanus installed?

**Comment by LittleExxGames** [comment] 2020-05-05 18:03
I had the same problem, but it was only after I installed scaling health to my mod pack. However, scaling health is not the cause paired only with this mod. I have been adding mods to a test mod pack one at a time to see what was causing it but I gave up after adding all the mods that I think would have even remotely interacted with Forbidden Arcanus. 
[crash-2020-05-05_11.59.51-client.txt](https://github.com/stal111/Forbidden-Arcanus/files/4582806/crash-2020-05-05_11.59.51-client.txt)

**Comment by Matthysse** [comment] 2020-05-16 08:16
It crashes with the exact same message on the latest Forge version 31.2.0

**Comment by JurnyJudasz** [comment] 2020-05-17 15:57
got the same problem.
[crash-2020-05-01_11.22.46-client.txt](https://github.com/stal111/Forbidden-Arcanus/files/4640540/crash-2020-05-01_11.22.46-client.txt)

**Comment by Piotr-Aueternum** [comment] 2020-05-17 19:13
MoreCrashInfo mod logs:
[crash-2020-05-17_21.09.12-client.txt](https://github.com/stal111/Forbidden-Arcanus/files/4640838/crash-2020-05-17_21.09.12-client.txt)

**Comment by LittleExxGames** [comment] 2020-05-17 22:35
traverse: Legacy continued, as of version 3.1.0, crashes with forbidden arcanus making this error. 
[crash-2020-05-17_16.33.40-client.txt](https://github.com/stal111/Forbidden-Arcanus/files/4641194/crash-2020-05-17_16.33.40-client.txt)

traverse: Legacy continued 3.0.0 worked fine with this mod.

**Comment by stal111** [comment] 2020-05-31 21:35
Should be fixed in 1.15.2-1.4-beta-1

**Closed as completed by stal111** 2020-05-31 21:35 UTC
