### ISSUE TITLE
Conflict with Apotheosis

### ISSUE THREAD

**Issue by Cadock** [stal111/Forbidden-Arcanus#188] opened 2021-09-16 07:20 UTC
When both Apotheosis and Forbidden & Arcanus are installed then spawner scrap does not drop when breaking spawners. Assuming this may be because Apotheosis replaces vanilla spawners with its own.

**Comment by charlielyne1** [comment] 2021-09-16 12:19
Having this issue too, playing Better Minecraft Plus. Scraps will not drop in the current version - v22

**Comment by stal111** [comment] 2021-09-17 13:02
Duplicate of #171

**Closed as completed by stal111** 2021-09-17 13:02 UTC
