### ISSUE TITLE
Forbidden and Arcanus not compatible with Domum Ornamentum

### ISSUE THREAD

**Issue by Sennario** [stal111/Forbidden-Arcanus#301] opened 2022-09-27 22:06 UTC
**Describe the bug**
When I add Forbidden and Arcanus (FA) to my modlist it breaks the Architects Cutter from Domum Ornamentum (DU). I can still access the GUI but I can no longer put Blocks into the slots.

**To Reproduce**
1. Place the Architects Cutter
2. Right Click it with some stone or wood blocks in invetory
3. Try to put the Blocks in one of the slots in the GUI

**Expected behavior**
Not only the Blocks from FA wont go in there, but also the vanilla blocks which normally work fine. 

**Versions**
 - Forbidden & Arcanus: 1.19.2-2.1.0-beta1
 - Valhelsia Core: 1.19.2-0.4.0
 - Forge: 43.1.27
 - Domum Ornamentum: 1.19-1.0.60-ALPHA

**Additional context**
This is my first report and I don't know if I should post this here or in the Issues of Domum Ornamentum. I think it could be a problem with the Tags, but I can't code myself. So I'm not sure.

**Comment by stal111** [comment] 2022-09-28 20:15
Please also report this to Domum Ornamentum. No idea what causes this yet.

**Comment by marchermans** [comment] 2022-10-02 12:13
I double checked my code, I have no idea either.
The GUI is just a normal container screen, like the stone cutter, but different....

**Comment by Zygus42** [comment] 2022-10-09 12:19
Can confirm problem - traced this after Domum's Stone Cutter was not working, making Minecolonies unusable.  In fact the Stonecutter has no recipes associated with it as long as Forbidden & Arcanus is also installed, otherwise is ok,  

Will attach logs:
[latest.log](https://github.com/stal111/Forbidden-Arcanus/files/9741536/latest.log)
[debug.log](https://github.com/stal111/Forbidden-Arcanus/files/9741539/debug.log)

**Comment by Zygus42** [comment] 2022-10-10 03:54
Updated Minecolonies and did some further testing with just Minecolonies and Forbidden.

Both on:
![2022-10-10_11 47 21](https://user-images.githubusercontent.com/20757445/194796861-713379a9-50d7-479e-8684-01742a71e0d6.png)
[latest.log](https://github.com/stal111/Forbidden-Arcanus/files/9743272/latest.log)
[debug.log](https://github.com/stal111/Forbidden-Arcanus/files/9743273/debug.log)

Just Minecolonies:
![2022-10-10_11 51 52](https://user-images.githubusercontent.com/20757445/194797054-6ca132f3-3f57-44df-a057-ad56cdb3e296.png)
[latest.log](https://github.com/stal111/Forbidden-Arcanus/files/9743276/latest.log)
[debug.log](https://github.com/stal111/Forbidden-Arcanus/files/9743277/debug.log)

File versions:
minecolonies-1.19.2-1.0.1064-BETA
minecolonies-blockui-1.19-0.0.64-ALPHA
minecolonies-domum_ornamentum-1.19-1.0.62-ALPHA-universal
minecolonies-multi-piston-1.19-1.2.16-ALPHA
minecolonies-structurize-1.19.2-1.0.452-ALPHA
forbidden_arcanus-1.19.2-2.1.0-beta1
forbidden_arcanus-valhelsia_core-forge-1.19.2-0.4.0
forge-1.19.2-43.1.25-installer

**Comment by gjerm** [comment] 2022-10-18 17:47
Another data point, where the recipes for the cutter appear to be empty, they're actually there, but invisible. I can pick out the blocks in creative, but when placed they are also invisible:

![image](https://user-images.githubusercontent.com/900483/196505804-dae2e7ef-f081-4378-b19d-6e87a4fbbac8.png)

![image](https://user-images.githubusercontent.com/900483/196506097-22389a45-8309-4032-b68f-79fe5f351b3d.png)

Mods:  
blockui-1.19-0.0.64-ALPHA  
domum_ornamentum-1.19-1.0.64-ALPHA-universal  
forbidden_arcanus-1.19.2-2.1.0-beta1  
minecolonies-1.19.2-1.0.1073-BETA  
structurize-1.19.2-1.0.453-ALPHA  
valhelsia_core-forge-1.19.2-0.4.0

**Comment by stal111** [comment] 2022-10-20 19:18
Fixed in forbidden_arcanus-1.19.2-2.1.0-beta2

**Closed as completed by stal111** 2022-10-20 19:18 UTC
Labels: Type: Bug, Status: Fixed For Next Release

**Comment by marchermans** [comment] 2022-10-21 03:58
What was the cause?

**Comment by stal111** [comment] 2022-10-21 17:27
When updating to 1.19 we renamed a bunch of items (Arcane Gold -> Deorum) and forgot to update a few old tags, thus failing to load. One of these was included in forge:storage_blocks which then also errored and as it seems you base your logic up on that tag.
