### ISSUE TITLE
Negative blood

### ISSUE THREAD

**Issue by mattba10** [stal111/Forbidden-Arcanus#379] opened 2023-12-02 10:02 UTC
**Describe the bug**
Somehow I got negative blood

**To Reproduce**
1. Use pipez mod
2. import full blood test tubes and allow all other slots to be empty
3. export empty test tubes

**Expected behavior**
Negative blood should not appear

**Screenshots**
Unfortunately I broke the forge and wont be trying to recreate the bug - but I can IF required load up a test world

**Versions**
 - Forbidden & Arcanus: 
forbidden_arcanus-1.20.1-2.2.3.jar
- atm9: 0.2.24
 - Forge: 47.2.8

**Additional context**
N/A

**Comment by mattba10** [comment] 2023-12-02 10:53
Update; did it again - no clue how; wasn't even using pipez mod - just putting blood in manually
![image](https://github.com/stal111/Forbidden-Arcanus/assets/124603841/ca1a32cb-866b-4b17-98b9-7b246261562d)

**Comment by stal111** [comment] 2023-12-14 11:16
Did this happen at a special amount? Currently trying to reproduce it but no luck so far.

**Comment by GiGDDragon** [comment] 2023-12-19 01:55
At 30k tier 4 blood becomes -35k then if you keep adding it goes to -15k which in total is the 50k worth of blood.

**Comment by SBshenqianye** [comment] 2023-12-19 07:35
![image](https://github.com/stal111/Forbidden-Arcanus/assets/51922539/e2ec6a89-86e6-4f13-bd0b-701506bc0710)
I also encountered this situation, I suspect the data type is too small

**Comment by SBshenqianye** [comment] 2023-12-19 07:49
![image](https://github.com/stal111/Forbidden-Arcanus/assets/51922539/c82cb741-b657-4dcf-9efe-398fd308d5a5)
new situation, when blood 'add' to -15536, no matter how much blood volume is added

**Comment by AbdeI1** [comment] 2024-01-10 07:26
They used a signed short for blood level 💀 (maybe just add 65536 to your negative number and see if that correctly correlates to the blood level). Also can confirm happens on atm9 0.2.32, forge: 47.2.16, jar version: 2.20.1-2.2.4 with just normally adding blood through blood vials.

**Comment by SiverDX** [comment] 2024-01-10 08:29
the only place where a short is used (in regards to rituals) is here 

https://github.com/stal111/Forbidden-Arcanus/blob/a3500d262c86fc6746172a8ca1b99904630b8ecf/src/main/java/com/stal111/forbidden_arcanus/common/block/entity/forge/ritual/RitualInput.java#L34

**Comment by stal111** [comment] 2024-01-10 09:28
I also thought of that behaviour being caused by using a short somewhere but I I haven't found anything problematic yet.
It's suspicious though that all reports so far have been using the Atm 9 pack. Did anyone had this problem with just f&a?

**Comment by Alaric323** [comment] 2024-02-28 19:30
I'm not using just F&A, but in a different pack (MineColonies Dimensional Adventure) I'm also experiencing this problem.  The blood value underflows, and continuously adding blood "maxes" out at -15536 as in SB's screenshot.

**Comment by SiverDX** [comment] 2024-02-28 19:56
i'd probably switch the usage of short to int here

https://github.com/stal111/Forbidden-Arcanus/blob/1.20.x/src/main/java/com/stal111/forbidden_arcanus/common/block/entity/forge/ritual/RitualInput.java

considering the amount is an int
and see if the issue persists

**Comment by The1368** [comment] 2024-03-10 21:31
> I also thought of that behaviour being caused by using a short somewhere but I I haven't found anything problematic yet. It's suspicious though that all reports so far have been using the Atm 9 pack. Did anyone had this problem with just f&a?

Not with just f&a, but in Valhelsia 6. When I manually added test tubes and it hit 30k on a tier 4 forge, it inverted into the negatives

**Comment by miapuffia** [comment] 2024-04-02 23:05
Temporary fix if cheats are enabled:

Stand on top of the forge and run
`/data modify block ~ ~-1 ~ Essences.blood set value 20000`
You might need to remove the -1 if it says target block is not a block entity

**Comment by zinerith** [comment] 2024-05-23 19:04
This issue is still unresolved in 1.20.1 currently. Was putting blood in manually via test tubes when it wrapped to the negatives around 30k blood with a Tier 4 forge. When will this get a fix I wonder?

**Comment by mattba10** [comment] 2024-06-15 13:52
Can confirm not resolved - did it today and got negative blood

**Comment by HeroBrianMack** [comment] 2024-07-17 03:54
@mattba10 have you tried with the newest version of the mod for 1.20.1 (2.26), as I have tried to replicate this issue and reached 50k blood with no issue.

**Comment by TheDieselPunk** [comment] 2024-09-26 02:37
The issue is still present for 1.20.1-2.2.6
![image](https://github.com/user-attachments/assets/1a325db4-7471-4585-ade4-5ed053485ec1)

**Comment by HeroBrianMack** [comment] 2024-09-26 21:29
@TheDieselPunk does this happen on a fresh world and with no other mods?

**Comment by SiverDX** [comment] 2024-09-26 21:37
the cause is already known:

![image](https://github.com/user-attachments/assets/182d0b93-0c95-44cd-8d98-a03ce5529c70)

1.21 apparently doesn't have this problem (and it's the active developed version)

**Comment by HeroBrianMack** [comment] 2024-09-26 23:22
That isn’t in the code in the current version on GitHub for 1.20.1-2.2.6, which is I’m asking. Maybe the GitHub updated without being uploaded on curseforge?

**Comment by SiverDX** [comment] 2024-09-27 05:30
> That isn’t in the code in the current version on GitHub for 1.20.1-2.2.6, which is I’m asking. Maybe the GitHub updated without being uploaded on curseforge?

that is vanilla code

**Comment by stal111** [comment] 2024-10-26 14:20
This got fixed in the 1.21.1 version of the mod.

**Closed as completed by stal111** 2024-10-26 14:20 UTC
Labels: Type: Bug

**Comment by Serega007RU** [comment] 2024-12-26 18:12
> Это было исправлено в версии мода 1.21.1.

@stal111 
please tell me how did you fix it? what specific commit did you make to fix it?
I can't upgrade to the new version of minecraft and I want (at least on my own) to fix this problem on version 1.20.1.
