### ISSUE TITLE
1.18.1 Crash

### ISSUE THREAD

**Issue by EndangeredBubs** [stal111/Forbidden-Arcanus#220] opened 2022-01-04 01:00 UTC
[crash-2022-01-03_16.54.23-client.txt](https://github.com/stal111/Forbidden-Arcanus/files/7804738/crash-2022-01-03_16.54.23-client.txt)

Crash log above.

**Comment by mewnn** [comment] 2022-01-05 22:38
[crash-2022-01-06_00.34.15-client.txt](https://github.com/stal111/Forbidden-Arcanus/files/7818175/crash-2022-01-06_00.34.15-client.txt)

same with me btw

**Comment by DailyHighlighter** [comment] 2022-01-06 14:24
It's likely related to this 
![Screenshot_20220106-092417_YouTube](https://user-images.githubusercontent.com/18130185/148397610-8bc1ffa9-5a79-49fd-a687-48962e12950b.jpg)

**Comment by willtarax** [comment] 2022-01-06 16:31
I doubt it... Seeing as how they said this issue is 1.18.1 and C:A&B is 1.16...

**Comment by stal111** [comment] 2022-01-09 19:51
Did some testing and it seems that this crash is caused by the mod Terrablender. Could anyone else test without that mod to verify it?

**Comment by Edel-Lilies** [comment] 2022-01-11 04:41
I just remove mod Terrablender and problem still exists.
[crash-2022-01-11_13.39.16-client.txt](https://github.com/stal111/Forbidden-Arcanus/files/7843753/crash-2022-01-11_13.39.16-client.txt)

**Comment by Edel-Lilies** [comment] 2022-01-11 07:51
Maybe the problem is mod CreateDeco.

**Comment by stal111** [comment] 2022-01-16 13:54
This issue should be fixed in version 1.18.1-2.0.1. Could anyone test the new release to verify the fix it working?

**Closed as completed** 2022-01-17 18:41 UTC
